### ISSUE TITLE
FYI

### ISSUE THREAD

**Issue by ararslan** [JuliaMath/OpenspecfunBuilder#5]
https://github.com/ararslan/openspecfun-builder. SpecialFunctions.jl is currently using this.

**Comment by KristofferC** [comment]
I am just trying stuff out. Also, I think it is better the community use the same framework instead of hand-rolling our own for each dependency.

**Comment by ararslan** [comment]
> I am just trying stuff out.

Sure, that's why it's just an FYI. 🙂

> Also, I think it is better the community use the same framework instead of hand-rolling our own for each dependency.

I 70% agree with that; I think in some cases it's fine for people to do whatever as long as it works. Granted my repo also predates a lot of the more recent usability stuff for BinaryBuilder, and at this point BinaryBuilder is obviously the better solution.

Anyway, like I said, FYI.
